### ISSUE TITLE
Huge Latency Issue with Chromecast

### ISSUE THREAD

**Issue by shubhamshah02** [dwaan/homebridge-adb#47]
**Describe the bug**
Two-second delay on every remote click on the Apple TV Remote section from Control Center.

**Expected behavior**
Button clicks should be quicker and more responsive, like the native Bluetooth remote which works very quick. Moving through the UI takes 2 seconds on every left/right/up/down click so it can become very frustrating to use.

**Log output**
N/A

**Device (please complete the following information):**
 - Name: Chromecast with Google TV

**Additional context**
Using an iPhone X and iPad Pro 2020 with WiFi 5, full bars, and gigabit connection with the Chromecast in the same room, also with full bars. Also, I use Homebridge Bravia for another TV and there is no latency issue with that one so it's not the Raspberry Pi 3B+ I am using to host Homebridge.

**Comment by dwaan** [comment]
Hey, thank you for the report. This is a known bug that sadly can't be fix due to the limitation of the overall method of the connection. 

The homebridge-adb plugin use ADB shell command to communicate to the Android device, this connection have noticeable delay. I often tested the ADB command directly from my computer Terminal and it always produce approx 1 second delay on every command. 

From what I see, the Bravia plugins use a REST API that have faster direct connection to the TV. Similar to my LG TV using Homebridge WebOS, it have faster response than this plugin also.

**Comment by SpikePlayz** [comment]
Thanks for the response. What kind of system does the Android TV app use to control these devices? It seems much more snappy.

**Comment by dwaan** [comment]
They are using this protocols https://pro-bravia.sony.net/develop/integrate/ip-control/ 
So far I haven't seen any similar lightweight method for common Android device other than ADB, could be more useful if the have it.

**Comment by dwaan** [comment]
The latency are expected behavior using adb to connect to android device.
