### ISSUE TITLE
Can't find android tv when searching for accesories in Home app

### ISSUE THREAD

**Issue by ManioqTv** [dwaan/homebridge-adb#64]
Hello everyone
I am pretty new to homebridge and since I succesfully paired my Philipss TV with homekit, now I want to go further by integrating my nvidia shield wich is my main device for media consumption. I followed the step and I think all the config are good since I have my nvidia shield in my homebridge dashboard. My issue is when I try to add my shield as accesory in home app, there is nothing to add.
Any idea ? Thanks in advance

![IMG_0523](https://user-images.githubusercontent.com/96415830/146777415-3070b454-0108-4003-8403-3b5d93082ecc.png)
![image_2021-12-20_145039](https://user-images.githubusercontent.com/96415830/146777419-2ee27441-4bde-46e6-bbe8-27c9df85e99c.png)

**Comment by dwaan** [comment]
Hello, it looks like it should be working. 

Have you tried to restart your homebridge server and see if it will appeared after that.

**Comment by ManioqTv** [comment]
Yeah I have tried to reboot my homebridge, and after restart I have these :
![Uploading image_2021-12-20_152442.png…]()
Log spamming message that device can't be found, so I have to run adb connect again everytime I restart my homebridge
![image](https://user-images.githubusercontent.com/96415830/146782534-7a634dd2-bd95-490c-99ba-21d4ce077274.png)

But still nothing when adding accessory

**Comment by dwaan** [comment]
You can disable the debug log via Homebridge Config UI X and uncheck the "display more debug message" or add "debug: false" in your Config file, if you don't want to see the logs. 

That screenshot means that homebridge-adb can't connect to your device, either because of wrong ip, device is turned off, network trouble, or adb not properly authorized. So it won't create the HomeKit accessories until it can successfully connect. 

One possible solution: make sure you turn on your Shield, open terminal via Homebridge Config UI X, then type "adb devices". You can also restart Homebridge just to make sure. If your device listed there, then the plugin should work, theoretically. If not, then you need to authorized your adb connection, please refer to readme on how to do that. 

Side note: You don't have to reconnect ADB every time you restart Homebridge. The plug-ins will reconnect to ADB, provided it with correct IP address.

**Comment by ManioqTv** [comment]
so here what I did
- Shield TV ON
- Restarted my homebridge server
- type adb devices -> result nothing my nvidia shield was disconnected after reboot .... and log spamming"SHIELD - Device disconnected? Trying to reconnect"
- I have to type adb connect 192.168.1.61:55 to reconnect my shield tv...
- Shield TV still ON
- Trying to add accessory in the home app, nothing in the home app but Nvidia shield is present in my homebridge dashboard

So I have 2 issues:
- device disconnecting from adb devices list after homebrige reboot. 
- And Shield is not showing in Home App

**Comment by ManioqTv** [comment]
- Resolved my issue about Home app not discovering nvidia shield TV
For unknown reason when my accessory has the name "SHIELD" it doesn't work, but renamed to SHIELDTV, now I can find it in home app
- But the 2nd persist, my nvidia shield keep disconnecting from homebridge when I restart my server. Where I can find the config/startup.sh please ? I'am running homebridge img on a raspberry

**Comment by dwaan** [comment]
> * Resolved my issue about Home app not discovering nvidia shield TV
>   For unknown reason when my accessory has the name "SHIELD" it doesn't work, but renamed to SHIELDTV, now I can find it in home app
> * But the 2nd persist, my nvidia shield keep disconnecting from homebridge when I restart my server. Where I can find the config/startup.sh please ? I'am running homebridge img on a raspberry

Reminder, this is not ideal solution:

Yes, you can run "adb connect ..." on OS startup, to make sure ADB properly connecting to your device.

If you're running docker image in your rpi. Only then you can accessed  startup.sh from three dots menu in Homebridge Config UI X
<img width="287" alt="Screen Shot 2021-12-22 at 15 57 30" src="https://user-images.githubusercontent.com/1238465/147103972-7725e169-8168-4bda-8abb-4442a2cb1862.png">
You can add your "adb connect ..." over there. 

If you're running homebridge image and flash it to SD card, there is no startup.sh, but instead you can use regular linux startup methods like crontab to execute a command on startup.
